# Generated by Django 5.0.2 on 2024-02-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_is_registrated_registration_is_registered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
