# Generated by Django 5.0.2 on 2024-02-26 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('enrollment', '0002_alter_registration_is_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='enrollment', to='enrollment.registration'),
        ),
    ]
