# Generated by Django 5.0.2 on 2024-02-26 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_assessment_name'),
        ('enrollment', '0003_alter_registration_sig_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enrollment.registration'),
        ),
    ]
