# Generated by Django 5.0.2 on 2024-02-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('sig_register', models.CharField(max_length=11, unique=True)),
                ('ocupation', models.CharField(choices=[('Ex', 'Público Externo'), ('E', 'Estudante'), ('F', 'Funcionário')], max_length=2)),
                ('is_registered', models.BooleanField()),
            ],
        ),
    ]
