# Generated by Django 5.0.2 on 2024-02-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_alter_registration_is_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='sig_register',
            field=models.CharField(max_length=11),
        ),
    ]
